name: Download
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  Download:
    name: Download
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Preparing
        run: |
          pip install -r requirements.txt
      - name: Download
        run: python download.py
        env:
          LINKS: ${{ vars.LINKS }}
          LINKS01: ${{ vars.links01 }}
      - name: Keep workflow run
        uses: liskin/gh-workflow-keepalive@v1
